services:
  - type: web
    name: hamsog
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: DATA_DIR
        value: /opt/render/project/src/data
